6 get /api/reviews/review id/comments
CharlieH94/be-nc-games pull request #5
Opened 2023-02-21 15:10 UTC by CharlieH94

2023-02-21 15:31 UTC, Slyose requested changes

2023-02-21 15:31 UTC, Slyose commented on sandbox.sql
> +SELECT * FROM comments WHERE review_id = 2 ORDER BY created_at DESC;
Seems like a good idea to have this file in the .gitignore :)

2023-02-21 15:31 UTC, Slyose commented on __tests__/app.test.js
> +  describe("GET /api/reviews/:review_id/comments", () => {
Great testing so far, but also needs error handling to be tested:
A 404 for an id with no reviews
a 400 for an invalid id e.g /api/reviews/**egg**/comments
And finally, a 200 for a review with no comments, that should respond with an empty array of comments

2023-02-21 15:34 UTC, CharlieH94 commented on sandbox.sql
> +SELECT * FROM comments WHERE review_id = 2 ORDER BY created_at DESC;
I thought I had but obviously didn't do it right ha

2023-02-22 08:55 UTC, HannahBurks approved these changes
Hey Charlie. That is fine, you can merge that now. Nice work! 😄  The reason you have two different things for ID is if an ID does not exist it should throw a 404 but if it is the case the ID exists, there is  just no comments made yet, it should give an empty array :)

2023-02-22 11:04 UTC, merged

2023-02-22 11:08 UTC, cjplatten commented
All good